spring:
  datasource:
    username: root
    password: mysql3307
    url: jdbc:mysql://8.130.179.210:3306/hotelintelligencesystem?useAffectedRows=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  sql:
    init:
      mode: never
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
mybatis-plus:
  configuration:
    # 驼峰
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:mapper/**/*Mapper.xml
  global-config:
    # 逻辑删除配置
    db-config:
      # 未删除
      logic-not-delete-value: 0
      # 删除
      logic-delete-value: 1
      # id类型
      id-type: id_worker_str

# token配置
jwt:
  # 令牌自定义标识
  header: Authorization
  # 令牌秘钥
  secret: 12d8sxsm+xswxyy+2d8sxswxyybmaik/2dwzmztbdwtb/3rggdxfnjppspaparggdxfnjppspapapa+hbgwjybqyl+++++
  # 令牌有效期（默认30分钟）
  expireTime: 3600000
  token-prefix: Bearer
server:
  port: 8081
